function [CI_lower, CI_upper] = bootstrap_freq_diff2(data_matrix, N)
% generated by ChatGPT

% calculate the observed difference between observed and expected frequencies
freq_diff_obs = sum(data_matrix(:,3) - data_matrix(:,1).*data_matrix(:,2));

% initialize a vector to store the differences
freq_diff = zeros(N,1);

% perform bootstrapping
for i = 1:N
    % generate a bootstrap sample by sampling with replacement from the data
    bootstrap_sample = datasample(data_matrix, size(data_matrix,1), 'Replace', true);

    % calculate the difference between observed and expected frequencies for the bootstrap sample
    freq_diff(i) = sum(bootstrap_sample(:,3) - bootstrap_sample(:,1).*bootstrap_sample(:,2));
end

% calculate the 95% confidence intervals
alpha = 0.05;
CI_lower = freq_diff_obs - prctile(freq_diff, 100*(1-alpha/2));
CI_upper = freq_diff_obs - prctile(freq_diff, 100*alpha/2);

end
